apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
  - image: callme-service
    jib:
      args:
        - -Pjib
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/deployment.yaml
